### PR TITLE
doc: fix overscroll plugin import

### PR DESCRIPTION
**Pull request by hongbo-miao**

### CODE REVIEW

**Comment by dolphin-wood** [comment]
Ah, stupid me XD

**Comment by dolphin-wood** [comment]
By the way, this project is not actively maintained now. I'd suggest you write your own react wrap in your project 😃.

**Comment by hongbo-miao** [comment]
Oh, really.. I was trying to figure out how to do it in React of the method you provided, https://github.com/idiotWu/smooth-scrollbar/issues/118

**Comment by dolphin-wood** [comment]
Hmmm...it's a little bit difficult to update options in order during one lifecycle. What about turning off overscroll plugin on initializing:

```js
// child scrollbar
<Scrollbar plugins={{ overscroll: false }} ...>
```

**Comment by hongbo-miao** [comment]
Thanks, I tried first method and it worked!

```js
 componentDidMount() {
    const { scrollbar } = this.refs.scrollbarContainer;

    scrollbar.updatePluginOptions('overscroll', {
      effect: false,
    });

    scrollbar.options.continuousScrolling = true;
  }
```

Post here in case someone needs.

**Comment by hongbo-miao** [comment]
Oh, never mind, missed your message, that way is much cleaner.. Thank you so much!
```jsx
<Scrollbar plugins={{ overscroll: false }} ...>
```

**Pull request merged**
